# Generated by Django 4.1.7 on 2023-02-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tables',
            new_name='Table',
        ),
    ]
